### ISSUE TITLE
Model_training

### ISSUE THREAD

**Issue by Luoadore** [nku-palette/palette#11]
# 进度总结（About model servering） 

## 并加载预训练好的模型继续训练。

但是出了一个bug：

`  Traceback (most recent call last):
  File "object_detection/train.py", line 184, in <module>
    tf.app.run()
  File "/home/luo/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "object_detection/train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/media/luo/cs/master/models/research/object_detection/trainer.py", line 274, in train
    train_config.prefetch_queue_capacity, data_augmentation_options)
  File "/media/luo/cs/master/models/research/object_detection/trainer.py", line 59, in create_input_queue
    tensor_dict = create_tensor_dict_fn()
  File "object_detection/train.py", line 121, in get_next
    dataset_builder.build(config)).get_next()
  File "/media/luo/cs/master/models/research/object_detection/builders/dataset_builder.py", line 186, in build
    process_fn, config.input_path[:], input_reader_config)
  File "/media/luo/cs/master/models/research/object_detection/utils/dataset_util.py", line 141, in read_dataset
    sloppy=config.shuffle))
  File "/home/luo/anaconda3/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 960, in apply
    dataset = transformation_func(self)
  File "/home/luo/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/data/python/ops/interleave_ops.py", line 76, in _apply_fn
    buffer_output_elements, prefetch_input_elements)
  File "/home/luo/anaconda3/lib/python3.6/site-packages/tensorflow/python/data/ops/readers.py", line 163, in __init__
    self._map_func.add_to_graph(ops.get_default_graph())
  File "/home/luo/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 488, in add_to_graph
    self._create_definition_if_needed()
  File "/home/luo/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 321, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/home/luo/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 338, in _create_definition_if_needed_impl
    outputs = self._func(*inputs)
  File "/home/luo/anaconda3/lib/python3.6/site-packages/tensorflow/python/data/ops/readers.py", line 151, in tf_map_func
    dataset = map_func(nested_args)
  File "/home/luo/anaconda3/lib/python3.6/site-packages/tensorflow/python/data/ops/readers.py", line 244, in __init__
    filenames = ops.convert_to_tensor(filenames, dtype=dtypes.string)
  File "/home/luo/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 950, in convert_to_tensor
    as_ref=False)
  File "/home/luo/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1040, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/luo/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 883, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype string for Tensor with dtype float32: 'Tensor("arg0:0", shape=(), dtype=float32)'`

### 明天我继续修改

**Comment by zeanyon** [comment]
我也是这个问题诶
